DROP TABLE IF EXISTS NOTES;  
CREATE TABLE NOTES (  
Id INT PRIMARY KEY,  
QUESTION CLOB NOT NULL,  
INPUT_QUESTION CLOB NOT NULL,  
OUTPUT_EXPLAINATION CLOB NOT NULL,  
INTUITION CLOB NOT NULL , 
CODE CLOB NOT NULL ,
CATEGORY INT(8) NOT NULL 
);  

DROP TABLE IF EXISTS CATEGORY;  
CREATE TABLE CATEGORY (  
Id INT PRIMARY KEY,  
NAME  VARCHAR(50) NOT NULL
);  